# Generated by Django 4.1.2 on 2022-10-24 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=70)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('description', models.TextField(max_length=300)),
                ('assignees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
